# Generated by Django 5.2.11 on 2026-04-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_steps/'),
        ),
    ]
