# Generated by Django 5.2.11 on 2026-02-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='diabetic_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
