# Generated by Django 5.2.11 on 2026-02-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_recipe_diabetic_friendly'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='No instructions yet'),
            preserve_default=False,
        ),
    ]
