# Generated by Django 5.2.11 on 2026-02-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_recipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='No instructions yet'),
        ),
    ]
