# Generated by Django 5.2.11 on 2026-03-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='lactose_free',
            field=models.BooleanField(default=False),
        ),
    ]
