# Generated by Django 5.2.11 on 2026-03-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_recipe_gluten_free_recipe_lactose_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='healthy',
            field=models.BooleanField(default=True),
        ),
    ]
